import { cn } from '@/lib/utils/cn';

/**
 * The DUMA brand mark. It carries its own tile, so it *replaces* an
 * icon-in-a-box lockup rather than sitting inside one, and it holds its brand
 * colours in both themes (a logo that changes colour with the theme stops being
 * a logo).
 *
 * Two grounds, one geometry:
 *   default — forest tile, white monogram (9.87:1). For light surfaces.
 *   onDark  — white tile, forest monogram. For the green shell (sidebar, the
 *             auth panel), where a forest tile would vanish into the column.
 *
 * The tile was apricot until green became the action colour. A brand mark in the
 * one hue that now means "order data" put the logo outside its own system.
 *
 * Inlined rather than `<img src="/logo.svg">` so it costs no request and can't
 * flash in after paint on the sign-in screen. Decorative by design: every
 * lockup pairs it with the visible "DUMA" wordmark, so announcing it again
 * would only repeat.
 *
 * Source assets: public/logo.svg (default), public/logo_white_green.svg
 * (onDark), public/icon.svg (PWA + browser tab), public/icon-maskable.svg
 * (Android adaptive), and two rasters baked from those — app/favicon.ico
 * (16/32/48/256, from logo.svg) and public/apple-icon.png (180, from the
 * maskable variant, because iOS ignores an SVG touch icon). Change the geometry
 * in one and it has to change in all of them — a manifest can't read an inline
 * component, a component can't be fetched, and the two PNG/ICO rasters have to
 * be regenerated by hand.
 */
const GROUNDS = {
  default: { tile: '#174C38', mark: 'white' },
  onDark: { tile: 'white', mark: '#174C38' },
} as const;

export function Logo({
  size = 36,
  variant = 'default',
  className,
}: {
  size?: number;
  variant?: keyof typeof GROUNDS;
  className?: string;
}) {
  const { tile, mark } = GROUNDS[variant];

  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 36 36"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={cn('shrink-0', className)}
      aria-hidden="true"
      focusable="false"
    >
      <rect width="36" height="36" rx="7" fill={tile} />
      <path
        d="M31 25.3125C31 28.4536 28.4579 30.9999 25.3219 31L10.315 30.9993C3.71595 30.9995 3.03058 21.3436 9.56316 20.4087L18.6342 19.7697C22.4213 19.2276 23.249 14.118 19.8273 12.4044C16.1443 10.5599 17.4547 4.99982 21.5725 4.99982H26.0425C28.7805 4.99982 31 7.22298 31 9.96541V25.3125Z"
        fill={mark}
      />
      <path
        d="M14.7773 15.9697C14.7773 14.4017 16.0485 13.126 17.6165 13.126V13.126C19.1845 13.126 20.4556 14.4017 20.4556 15.9697V15.9697C20.4556 17.5377 19.1845 18.8135 17.6165 18.8135V18.8135C16.0485 18.8135 14.7773 17.5377 14.7773 15.9697V15.9697Z"
        fill={mark}
      />
      <path
        d="M5.04297 7.97795C5.04297 6.33381 6.37581 5.00098 8.01994 5.00098H18.833L18.5072 5.21855C16.2036 6.75677 15.9644 10.0526 18.0218 11.9072L7.74162 10.9419C6.21204 10.7983 5.04297 9.51426 5.04297 7.97795Z"
        fill={mark}
      />
    </svg>
  );
}
