// Country options for address entry — UK first (primary market), then a broad
// common set. Values are the display names (stored as part of the combined
// single-line address).
export const COUNTRIES = [
  'United Kingdom',
  'Ireland',
  'United States',
  'Ukraine',
  'Canada',
  'Australia',
  'New Zealand',
  'France',
  'Germany',
  'Spain',
  'Italy',
  'Portugal',
  'Netherlands',
  'Belgium',
  'Luxembourg',
  'Switzerland',
  'Austria',
  'Denmark',
  'Sweden',
  'Norway',
  'Finland',
  'Iceland',
  'Poland',
  'Czechia',
  'Slovakia',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Greece',
  'Croatia',
  'Slovenia',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Turkey',
  'India',
  'Pakistan',
  'Bangladesh',
  'China',
  'Japan',
  'South Korea',
  'Singapore',
  'Hong Kong',
  'United Arab Emirates',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Brazil',
  'Mexico',
] as const;

export const DEFAULT_COUNTRY = 'United Kingdom';
